In [1]:
import gensim
from gensim.models import Word2Vec, KeyedVectors

In [2]:
from google.colab import drive
drive.mount('/content/drive/')

Mounted at /content/drive/


In [4]:
model = KeyedVectors.load_word2vec_format('/content/drive/MyDrive/GoogleNews/GoogleNews-vectors-negative300.bin.gz',binary=True,limit=500000)

In [5]:
model['human']

array([ 5.59082031e-02,  9.22851562e-02,  1.07910156e-01,  2.83203125e-01,
       -2.43164062e-01,  1.90429688e-02,  4.08203125e-01, -3.17382812e-02,
       -4.78515625e-02,  6.34765625e-02, -9.32617188e-02, -4.46777344e-02,
       -2.41210938e-01, -1.58203125e-01, -5.83496094e-02,  2.51953125e-01,
       -3.24707031e-02,  1.00097656e-01, -4.56542969e-02,  1.35742188e-01,
       -2.07031250e-01, -3.73046875e-01,  4.39453125e-02,  4.24804688e-02,
        6.93359375e-02, -2.42187500e-01, -2.75390625e-01,  1.95312500e-01,
        2.26562500e-01, -1.90429688e-01, -2.35351562e-01, -5.56640625e-02,
       -1.25000000e-01, -8.78906250e-02, -2.33398438e-01,  9.61914062e-02,
       -4.83398438e-02,  4.54101562e-02,  9.81445312e-02,  5.76171875e-02,
       -4.17480469e-02,  2.02148438e-01, -9.03320312e-02,  2.75390625e-01,
       -6.34765625e-02,  4.93164062e-02,  2.92968750e-02,  2.57812500e-01,
        1.32812500e-01,  7.42187500e-02,  6.64062500e-02, -1.37695312e-01,
       -1.73828125e-01,  

In [6]:
model['human'].shape

(300,)

In [7]:
model['man']

array([ 0.32617188,  0.13085938,  0.03466797, -0.08300781,  0.08984375,
       -0.04125977, -0.19824219,  0.00689697,  0.14355469,  0.0019455 ,
        0.02880859, -0.25      , -0.08398438, -0.15136719, -0.10205078,
        0.04077148, -0.09765625,  0.05932617,  0.02978516, -0.10058594,
       -0.13085938,  0.001297  ,  0.02612305, -0.27148438,  0.06396484,
       -0.19140625, -0.078125  ,  0.25976562,  0.375     , -0.04541016,
        0.16210938,  0.13671875, -0.06396484, -0.02062988, -0.09667969,
        0.25390625,  0.24804688, -0.12695312,  0.07177734,  0.3203125 ,
        0.03149414, -0.03857422,  0.21191406, -0.00811768,  0.22265625,
       -0.13476562, -0.07617188,  0.01049805, -0.05175781,  0.03808594,
       -0.13378906,  0.125     ,  0.0559082 , -0.18261719,  0.08154297,
       -0.08447266, -0.07763672, -0.04345703,  0.08105469, -0.01092529,
        0.17480469,  0.30664062, -0.04321289, -0.01416016,  0.09082031,
       -0.00927734, -0.03442383, -0.11523438,  0.12451172, -0.02

In [8]:
model.most_similar('man')

[('woman', 0.7664012908935547),
 ('boy', 0.6824871301651001),
 ('teenager', 0.6586930155754089),
 ('teenage_girl', 0.6147903203964233),
 ('girl', 0.5921714305877686),
 ('robber', 0.5585119128227234),
 ('Robbery_suspect', 0.5584409832954407),
 ('teen_ager', 0.5549196600914001),
 ('men', 0.5489763021469116),
 ('guy', 0.5420035123825073)]

In [9]:
model.most_similar('keyboard')

[('keyboards', 0.7883305549621582),
 ('Keyboard', 0.7165083289146423),
 ('touchpad', 0.7082577347755432),
 ('trackpad', 0.7039602994918823),
 ('keypad', 0.6944352984428406),
 ('qwerty_keyboard', 0.6921881437301636),
 ('stylus', 0.6857424378395081),
 ('Qwerty_keyboard', 0.6761177182197571),
 ('scroll_wheel', 0.6746445894241333),
 ('onscreen_keyboard', 0.6673976182937622)]

In [10]:
model.most_similar('cricket')

[('cricketing', 0.8372225761413574),
 ('cricketers', 0.8165745735168457),
 ('Test_cricket', 0.8094819188117981),
 ('Twenty##_cricket', 0.8068488240242004),
 ('Twenty##', 0.7624265551567078),
 ('Cricket', 0.75413978099823),
 ('cricketer', 0.7372578382492065),
 ('twenty##', 0.7316356897354126),
 ('T##_cricket', 0.7304614186286926),
 ('West_Indies_cricket', 0.6987985968589783)]

In [11]:
model.similarity('man','woman')

0.76640123

In [12]:
model.similarity('man','python')

0.2097966

In [15]:
model.doesnt_match(['JAVA','python','elephant'])

'JAVA'

In [16]:
x = model['king'] - model['man'] + model['woman']

In [18]:
model.most_similar([x])

[('king', 0.8449392318725586),
 ('queen', 0.7300517559051514),
 ('monarch', 0.645466148853302),
 ('princess', 0.6156251430511475),
 ('crown_prince', 0.5818676352500916),
 ('prince', 0.5777117609977722),
 ('kings', 0.5613663792610168),
 ('sultan', 0.5376775860786438),
 ('queens', 0.5289887189865112),
 ('ruler', 0.5247419476509094)]

In [19]:
model['king'][0:50]

array([ 0.12597656,  0.02978516,  0.00860596,  0.13964844, -0.02563477,
       -0.03613281,  0.11181641, -0.19824219,  0.05126953,  0.36328125,
       -0.2421875 , -0.30273438, -0.17773438, -0.02490234, -0.16796875,
       -0.16992188,  0.03466797,  0.00521851,  0.04638672,  0.12890625,
        0.13671875,  0.11279297,  0.05957031,  0.13671875,  0.10107422,
       -0.17675781, -0.25195312,  0.05981445,  0.34179688, -0.03112793,
        0.10449219,  0.06176758,  0.12451172,  0.40039062, -0.32226562,
        0.08398438,  0.0390625 ,  0.00585938,  0.0703125 ,  0.17285156,
        0.13867188, -0.23144531,  0.28320312,  0.14257812,  0.34179688,
       -0.02392578, -0.10986328,  0.03320312, -0.0546875 ,  0.01531982],
      dtype=float32)

In [20]:
import seaborn as sns
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# king, queen, woman, girl, boy, man, water
words = ['queen', 'woman', 'girl', 'boy', 'man', 'king', 'water']
embeddings = np.array([
    model['queen'][0:10],
    model['woman'][0:10],
    model['girl'][0:10],
    model['boy'][0:10],
    model['man'][0:10],
    model['king'][0:10],
    model['water'][0:10],
                       ])

df = pd.DataFrame(embeddings, index=words)

In [21]:
# Create a heatmap
plt.figure(figsize=(18,16))
heatmap = sns.heatmap(df, cmap='crest')
plt.show()